### ISSUE TITLE
License change from Apache 2 to BSD 3 clause

### ISSUE THREAD

**Issue by scott-wilson** [vfx-rs/openexr-bind#42]
In order to have the bindings ownership moved over to the OpenEXR project, we would need the following people to approve the license change. Please respond to the issue with something like "I approve the license change from Apache 2 to the OpenEXR project license (BSD 3 clause)", and we'll check off your name. Once everyone has approved the license change, we'll merge the PR. Also, the exact license to change to is https://github.com/AcademySoftwareFoundation/openexr/blob/master/LICENSE.md

- [x] Anders Langlands @anderslanglands 
- [x] Luke Titley @luke-titley 
- [x] Scott Wilson @scott-wilson 
- [x] Tiago Carvalho @tiago-lqt

**Comment by scott-wilson** [comment]
I approve the license change from Apache 2 to the OpenEXR project license (BSD 3 clause)

**Comment by anderslanglands** [comment]
I approve the license change from Apache 2 to the OpenEXR project license (BSD 3 clause)

**Comment by tiago-lqt** [comment]
I approve the license change from Apache 2 to the OpenEXR project license (BSD 3 clause)

**Comment by luke-titley** [comment]
I approve the license change from Apache 2 to the OpenEXR project license (BSD 3 clause)
